# Generated by Django 5.1.4 on 2024-12-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_alter_historicalquestion_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquestion",
            name="section",
            field=models.CharField(
                choices=[
                    ("SECTION_D", "Section D"),
                    ("SECTION_C", "Section C"),
                    ("SECTION_E", "Section E"),
                    ("SECTION_B", "Section B"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="section",
            field=models.CharField(
                choices=[
                    ("SECTION_D", "Section D"),
                    ("SECTION_C", "Section C"),
                    ("SECTION_E", "Section E"),
                    ("SECTION_B", "Section B"),
                ],
                max_length=20,
            ),
        ),
    ]
